spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SBER_DB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update